---
name: Build and deploy to Firebase Hosting
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Build project
        env:
          VITE_FIRESTORE_API_KEY: ${{ secrets.VITE_FIRESTORE_API_KEY }}
          VITE_FIRESTORE_AUTH_DOMAIN: ${{ secrets.VITE_FIRESTORE_AUTH_DOMAIN }}
          VITE_FIRESTORE_PROJECT_ID: ${{ secrets.VITE_FIRESTORE_PROJECT_ID }}
          VITE_FIRESTORE_STORAGE_BUCKET: ${{ secrets.VITE_FIRESTORE_STORAGE_BUCKET }}
          VITE_FIRESTORE_MESSEGING_SENDER_FILE: ${{ secrets.VITE_FIRESTORE_MESSEGING_SENDER_FILE }}
          VITE_FIRESTORE_APP_ID: ${{ secrets.VITE_FIRESTORE_APP_ID }}
          VITE_FIRESTORE_MEASUREMENT_ID: ${{ secrets.VITE_FIRESTORE_MEASUREMENT_ID }}
          VITE_SENTRY_DSN: ${{ secrets.VITE_SENTRY_DSN }}
          VITE_BACKEND_API_URI: ${{ secrets.VITE_BACKEND_API_URI }}
        run: yarn build
      
      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
